version: '3.1'

services:
  db:
    image: mongo
    restart: always
    ports:
      - '${DB_PORT}:27017'
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - authors:/mongo:/data/db

volumes:
  authors:
