version: '3.1'

services:
  db:
    image: mongo
    restart: always
    container_name: authors-db
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - authors:/mongo:/data/db

volumes:
  authors:
