service: authors-service

provider:
  name: aws
  region: sa-east-1
  stage: prod

useDotenv: true

package:
  patterns:
    - '!**/**'
    - dist/main.js

functions:
  main:
    handler: dist/main.handler
    name: authors-service
    url: true
    runtime: nodejs20.x
    timeout: 15
    environment:
      MONGO_URI: ${env:MONGO_URI}
      POSTS_API_URL: ${env:POSTS_API_URL}
      NODE_ENV: prod
      SERVER_MODE: serverless

plugins:
  - serverless-offline
