service: authors-service

provider:
  name: aws
  region: sa-east-1
  stage: prod
  httpApi:
    id: ${env:API_GATEWAY_ID}

useDotenv: true

package:
  patterns:
    - '!**/**'
    - dist/**

functions:
  main:
    handler: dist/main.handler
    name: authors-service
    runtime: nodejs20.x
    timeout: 15
    events:
      - httpApi:
          path: '/authors'
          method: ANY
      - httpApi:
          path: '/authors/{proxy+}'
          method: ANY
      - sqs: arn:aws:sqs:sa-east-1:159107743549:authors-queue.fifo
    environment:
      NODE_ENV: prod
      SERVER_MODE: serverless
      MONGO_URI: ${env:MONGO_URI}
      AWS_BUCKET_NAME: ${env:AWS_BUCKET_NAME}
      AWS_BUCKET_REGION: ${env:AWS_BUCKET_REGION}
      POSTS_QUEUE_URL: ${env:POSTS_QUEUE_URL}

plugins:
  - serverless-offline
