service: authors-service

provider:
  name: aws
  region: sa-east-1
  stage: prod
  httpApi:
    id: ${env:API_GATEWAY_ID}

useDotenv: true

package:
  patterns:
    - '!**/**'
    - dist/**

functions:
  main:
    handler: dist/main.handler
    name: authors-service
    runtime: nodejs20.x
    timeout: 15
    events:
      - httpApi:
          path: '/authors'
          method: ANY
      - httpApi:
          path: '/authors/{proxy+}'
          method: ANY
    environment:
      MONGO_URI: ${env:MONGO_URI}
      NODE_ENV: ${env:NODE_ENV}
      SERVER_MODE: ${env:SERVER_MODE}

plugins:
  - serverless-offline
